# Generated by Django 4.1.7 on 2023-02-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('item_no', models.IntegerField()),
                ('item_description', models.CharField(max_length=1000)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=11)),
            ],
        ),
    ]
